- CHANGELOG.md
- src/authentication.jl
- src/userinfo.jl
- test/authentication.jl
- test/mocking.jl
When the username is not set in the `/api/v1` response (which can happen), that leads to an error and we then assume legacy compat for the APIs. This makes sure we extract the API version information from `/api/v1`, even if `username` is not set there. Also adds mocked tests for the various backend edge cases.
> fix(auth): set correct api version when username missing

- CHANGELOG.md
- Project.toml
- docs/make.jl
- src/JuliaHub.jl
- src/utils.jl
- test/utils.jl
It's actually quite easy to make `TimeZones.localzone` fail and throw. So to handle this edge case, we fall back to UTC. I also added a global to cache the local timezone, so that we wouldn't call the timezone determination logic over and over again.
> fix: fall back to UTC if `localzone()` fails

- .github/workflows/CI.yml
- README.md
- src/authentication.jl
- src/jobsubmission.jl
- test/jet.jl
Adds a simple JET.jl workflow to do some static checking. It just runs in `:typo` mode for now, since that one actually passes. I.e.
```julia
JET.test_package("JuliaHub"; target_defined_modules=true, mode=:type)
```
In addition, it also does an informational `:basic` pass, but that won't fail the workflow.
This should currently fail, but pass once #9 is merged.
> ci: add a JET.jl workflow

- test/jobs.jl
- test/packagebundler.jl
This should fix JuliaHub.jl in PkgEval, where it's currently failing because it gets `Pkg.add`ed: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-07/04/JuliaHub.primary.log
> test: fix permissions of PackageBundler test inputs

- .github/workflows/CI.yml
- src/jobs/jobs.jl
- src/jobs/logging-kafka.jl
- src/jobs/logging-legacy.jl
- src/jobs/logging.jl
- test/jet.jl
Expands the JET CI check by moving from the `:typo` mode to a custom filtering function. And it will also include a couple of fixes discovered by going through the JET list.
> fix: additional fixes from JET, expand the JET check

- CHANGELOG.md
- Project.toml
- src/jobs/jobs.jl
- src/jobsubmission.jl
- test/jobenvs/job-windows/script.jl
- test/jobenvs/job1/script.jl
- test/jobs-live.jl
- test/jobs.jl
* `name` -> `alias` in `submit_job` (with a deprecation)
* `extend_job` handles `200` `success: false` responses now
* The live job tests now print some at-infos, and also set a nice job alias (to make it easier to identify the jobs in the UI).
* Use `@__DIR__` in appbundle live tests.
* Also update the CHANGELOG and set version to `v0.1.3` for tagging.
> Assortment of job-related fixes and improvements

- CHANGELOG.md
- Project.toml
- src/datasets.jl
The `do`-form got fully deprecated in https://github.com/JuliaPackaging/JLLWrappers.jl/commit/112e560b41c77f5ccd1f230dc1a9f271ea24d967. This is actually causing the live tests to fail, because it's now printing an extra warning that the tests are not accounting for: https://github.com/JuliaComputing/JuliaHub.jl/actions/runs/5883816382/job/15957283336#step:7:121
> fix: do not use the deprecated JLL do form

- .github/workflows/julia_formatter.yml
Because the formatter action is a required check for merging, it will block the merge when only excluded paths like CI and Markdown files are edited (happened in #16, #17). We _can_ filter on `paths` when in runs against master though.
> ci: run JuliaFormatter on all PRs

- test/runtests.jl
Oversight from #22 -- when you set `JULIAHUBJL_LIVE_WINDOWS_TESTS=true`, then the `is_enabled` tests fail since it's designed to change the functions behavior. This patch makes sure we unset the environment variable in the tests.
> test: fix is_enabled test when env var is set

- .github/workflows/CI.yml
To avoid the CI failures seen in https://github.com/JuliaComputing/JuliaHub.jl/pull/26#issuecomment-1713952425
Note: this PR is from my personal fork. Here's also a version of this that runs on on "`main`", showing that the live tests do run if it's in this repo: https://github.com/JuliaComputing/JuliaHub.jl/tree/mp/fork-live-tests
Based on this answer: https://github.com/orgs/community/discussions/26829#discussioncomment-3253575
> ci: disable live tests on fork PRs

- CHANGELOG.md
- src/applications.jl
- test/applications.jl
- test/mocking.jl
Follows up on #31 and #32 with tests, but also fixes an error in `_api_registries`, where the function returns an `Any[]` and causes a method error down the line.
> Mocked tests for app job submission, fix type instability

- CHANGELOG.md
- src/jobsubmission.jl
- test/jobs-applications-live.jl
- test/runtests-live.jl
Applications require `appArgs` to be set. Also adds a live test that attempts to submit, start, and then stop a `JuliaHub IDE` job.
> fix: submitting application jobs

- test/jobs-live.jl
This should resolve the live test failures, and future-proof the tests against any future configuration problems.
> test(live): allow multiple default images for a product

- test/jobs-live.jl
We may want to re-enable this test in the future though.
> test(live): don't assume that kill is synchronous

- .github/workflows/CI.yml
This repo does not see daily activity, but it would be good to know early if something has started failing the tests (the live tests in particular).
> ci: run CI on a weekly schedule

- test/jobs-live.jl
It sometimes may take over 30 seconds for a job to be killed in CI and there's nothing reasonable we can do about it for now.
Adding this as a temporary measure.
> test(live): wait longer on job kill

- CHANGELOG.md
- Project.toml
- src/datasets.jl
- test/datasets-live.jl
- test/datasets.jl
- test/mocking.jl
Handles problematic dataset list backend responses more gracefully, by printing one warning per call, rather than throwing an error.
Also, unrelated to the main change, but makes the `auth` argument of the internal `_get_datasets` function positional, for consistency.
> fix: handle backend responses more gracefully in datasets requests

- test/jobenvs/job-dist/Manifest.toml
- test/jobenvs/job-dist/Project.toml
- test/jobenvs/job-dist/script.jl
- test/jobenvs/job1/Manifest.toml
- test/jobenvs/job1/Project.toml
- test/jobs-live.jl
- test/jobs.jl
JuliaHub jobs have a fixed Julia version (1.9 presently), so you need to make sure you submit a `Manifest.toml` that is compatible with it. However, the current live tests sometimes resolve things with the running Julia version, and we run the tests with a whole range of Julia versions. With nightly Julia builds, this now causes issues (specifically, the `StyledStrings` standard library is not available on older Julia versions).
* Use `script""noenv` for all the tests that submit simple scripts. Standard `script""` attaches the currently running environment, which may declare dependencies that are not valid when running with a different Julia version. Those tests don't require any packages.
* Turn the distributed tests into an appbundle with a pre-resolved environment.
* Update the `job1` …
> test: ensure consistent Julia environments in live job tests

- CHANGELOG.md
- Project.toml
- src/datasets.jl
progress=false disables rclone's progress printing
> feat: add progress kwarg for upload_dataset

- CHANGELOG.md
- Project.toml
- docs/src/reference/job-submission.md
- src/node.jl
- test/jobs.jl
- test/mocking.jl
The documentation says that `nodespec` returns the _smallest_ node, not necessarily the cheapest. This fixes the behavior where `nodespec` (and therefore `submit_job`) would pick the wrong node if there is a bigger, but cheaper one available, and clarifies the documentation.
It also makes the output for `nodespecs()` sorted, but that's an implementation detail, and hence not documented.
> fix: compare nodespecs based on ngpu/ncpu/mem first, before price

- docs/make.jl
- src/authentication.jl
- src/datasets.jl
- src/jobs/jobs.jl
- src/jobs/logging-kafka.jl
- src/jobs/logging-legacy.jl
- src/jobs/logging.jl
- src/jobsubmission.jl
- src/node.jl
- src/userinfo.jl
- src/utils.jl
- test/authentication.jl
- test/batchimages.jl
- test/datasets-live.jl
- test/datasets.jl
- test/jobs-live.jl
- test/mocking.jl
- test/packagebundler.jl
- test/utils.jl
It's not so much that we merged any incorrectly formatted code, but the trailing comma formatting got fixed in JuliaFormatting (https://github.com/domluna/JuliaFormatter.jl/commit/19e6074951101616c5e2c826f755dd397fd48e25; https://github.com/domluna/JuliaFormatter.jl/issues/815). There still are some incorrectly removed trailing commas though, due to: https://github.com/domluna/JuliaFormatter.jl/issues/829
> chore: fix Julia formatting

- .JuliaFormatter.toml
- test/jobs.jl
Another formatting PR. The CSTParser issue has been fixed, so no need to ignore `test/jobs.jl` anymore.
> chore: format test/jobs.jl

- .github/workflows/CI.yml
- test/aqua.jl
* `continue-on-error: true` means that the Aqua job was failing, but it didn't show up on CI (e.g. [here](https://github.com/JuliaComputing/JuliaHub.jl/actions/runs/9324670198/job/25670331246)).
* However, the errors are non-actionable, so I'm configuring Aqua to ignore these for now.
Hopefully we'll catch any future errors though.
> test: fix Aqua workflow

- .github/workflows/format-julia.yaml
I realized why the previous workflow did not have `on.pull_request.path` (https://github.com/JuliaComputing/JuliaHub.jl/commit/354e28992535b7021d4f23ceac22fa00cf7251d0#diff-9a9d70a0eb6f3494fd934c224bf0867c14b00d46fde8bcc4d65bb2d836898946L9) -- it's a required check, so we need to run in on all PRs, even if they don't modify Julia files.
> ci: run Julia formatter on all PRs

- src/jobsubmission.jl
With probably 1.11, we started getting a
```
JET: JET-test failed at /home/runner/.julia/packages/JET/zHVn3/src/JET.jl:107[8](https://github.com/JuliaComputing/JuliaHub.jl/actions/runs/11589518895/job/32265190402?pr=74#step:6:9)
Expression: (JET.report_package)("JuliaHub"; toplevel_logger = nothing, report_config = JuliaHubReportFilter())
═════ 1 possible error found ═════
┌ submit_job(app::JuliaHub.AbstractJobConfig; ncpu::Integer, ngpu::Integer, memory::Integer, nnodes::Union{…}, elastic::Bool, process_per_node::Bool, auth::JuliaHub.Authentication, kwargs...) @ JuliaHub /home/runner/work/JuliaHub.jl/JuliaHub.jl/src/jobsubmission.jl:1186
│┌  @ JuliaHub /home/runner/work/JuliaHub.jl/JuliaHub.jl/src/jobsubmission.jl:118[9](https://github.com/JuliaComputing/JuliaHub.jl/actions/runs/115895188 …
```
> test: work around missing method error in JET

- CHANGELOG.md
- Project.toml
- src/datasets.jl
- test/datasets.jl
The `update_dataset` function (and by extension, `upload_dataset`) should, according to the documentation, accept `license = (:fulltext, ...)` when you want to set a custom license. However, this was currently implemented as `(:text, ...)`, and `:fulltext` would throw an error.
This PR fixes the implementation to correctly follow the docs and accept `license = (:fulltext, ...)`. We also keep supporting `license = (:text, ...)` as a deprecated argument as well, since this doesn't cost us much. It also adds test coverage for the `license` argument.
> fix: correctly allow for `license=(:fulltext, ...)` in update_dataset

- src/authentication.jl
I got a bit confused, thought this documentation might be useful
> docs: mention what `server` is in `JuliaHub.authenticate`

- src/jobs/logging.jl
Fix #78. The documented name immediately errors, so it's not breaking to just fix the docs here.
> docs: fix 'stream' argument for job_logs_buffered

- CHANGELOG.md
- Makefile
- docs/src/guides/datasets.md
- src/datasets.jl
- test/datasets.jl
This makes sure that the short `DatasetVersion` string representation is a valid Julia code:
```
julia> dataset.versions
2-element Vector{JuliaHub.DatasetVersion}:
JuliaHub.dataset(("username", "example-dataset")).versions[1]
JuliaHub.dataset(("username", "example-dataset")).versions[2]
```
Also fix a doctest in the `DatasetVersion` docstring, which now in turn exercises the `show` methods for `DatasetVersion`. Also, add a `fix-doctests` Make command.
> feat: make DatasetVersion repr valid Julia code

- src/datasets.jl
- src/utils.jl
- test/datasets.jl
- test/mocking.jl
- test/utils.jl
`datasets()` will filter out any dataset JSON objects it can not parse, just to gracefully degrade when there is something weird in the backend response, but only for _some_ datasets. However, currently it also hides e.g. any coding errors in the `Dataset()` constructor, because we catch things unconditionally.
This changes `Dataset` to consistently throw `JuliaHubError` when it encounters a backend response it can not parse, and `datasets()` will then only filter those datasets. Any other errors will get rethrown, making `datasets()` itself throw, directly exposing non-backend issues to the caller.
It also adds direct test coverage on the error handling in `Dataset(::Dict)` calls, which in turn required some slightly refactoring of the mocking code (to reuse the bit that constructs the …
> refactor: do not swallow non-backend errors in datasets()

- src/JuliaHub.jl
- src/authentication.jl
- src/utils.jl
- test/utils.jl
Setting `_LOCAL_TZ` in `__init__` adds a 100-200ms lag to doing `using JuliaHub`. Without it, loading the `JuliaHub` module becomes effectively instantaneous.
There is a theoretical behavior change here, where if you change `ENV["TZ"]` at the right place, you could potentially be using a different timezone. So I added a call to `_localtz` in `_authenticate`, to ensure that we set the global as soon as the user does basically anything with JuliaHub.jl.
> perf: do not initialize _LOCAL_TZ in __init__

- test/datasets-live.jl
- test/userInfo.gql
* Remove the `/user/groups` REST endpoint support in the tests. That endpoint was removed in 6.4.
* Use a newer query that correctly filters out old group memberships. It was added in 6.7, so the test suite will only work against 6.7 now.
> test: use newer UserInfo GQL query in tests

- CHANGELOG.md
- src/batchimages.jl
- src/jobsubmission.jl
- test/mocking.jl
Image options are being extended by tag and sha.
Previously an image option would be an image key and a type.
Now optionally an `image_tag` or `image_sha` field can appear in the image option and they should be used in job submission if chosen.
The other bigger change is that the unique constraint on options is no longer just the key, but now it's a unique constraint on key, tag and sha. This means the same key can appear multiple times with different tag/sha combinations.
This should be nonbreaking in any direction. Older client ignores the tag/sha and will just list another option with the same key. Older instances will never send tag/sha so using a newer client there is ok too.
> feat: receive and use tags in image options
